In [2]:
import numpy as np

print(np.__version__)

2.1.3


In [3]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
# Output: [1 2 3 4 5]

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)  # Output: (2, 2, 2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
zeros= np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
full = np.full((2,3),'Shape of you')
full

array([['Shape of you', 'Shape of you', 'Shape of you'],
       ['Shape of you', 'Shape of you', 'Shape of you']], dtype='<U12')

In [7]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
linespace = np.linspace(-10,10,5)
print(linespace)

[-10.  -5.   0.   5.  10.]


In [9]:
arange = np.arange(13)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
random = np.random.rand(3,4)
random

array([[0.11506711, 0.11567638, 0.87639423, 0.06861009],
       [0.39226096, 0.08270948, 0.62005272, 0.57844728],
       [0.19942276, 0.45330233, 0.64945441, 0.26049311]])

In [11]:
randint = np.random.randint(0,50,(3,3))
randint

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [12]:
nrmal = np.random.normal(10,5,(3,3))
nrmal

array([[ 6.76537876, 14.57694017, 18.86891099],
       [ 6.90618429, 12.27700209,  7.28513376],
       [11.22049016, 19.95263728, 16.11863894]])

In [13]:
arr=randint

In [14]:
arr

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.ndim

2

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr.nbytes

36

In [20]:
arr.sum()

np.int64(254)

In [21]:
arr.mean()

np.float64(28.22222222222222)

In [22]:
arr.std()

np.float64(9.975278083317084)

In [23]:
arr.min()

np.int32(14)

In [24]:
arr.var()

np.float64(99.50617283950618)

In [25]:
arr.max()

np.int32(45)

In [26]:
arr.argmax()

np.int64(7)

In [27]:
arr.argmin()

np.int64(6)

In [28]:
arr.sum(axis=1)

array([82, 89, 83])

In [29]:
arr.sum(axis=0)

array([ 58, 117,  79])

In [30]:
arr

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [31]:
np.arange(12).reshape(3,4)
np.arange(12).reshape(3,4).shape

(3, 4)

In [32]:
arr

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [33]:
arr.ravel()

array([27, 36, 19, 17, 36, 36, 14, 45, 24], dtype=int32)

In [34]:
arr.flatten()

array([27, 36, 19, 17, 36, 36, 14, 45, 24], dtype=int32)

In [35]:
arr1 = np.array([1, 2, 3, 4])

In [36]:
np.resize(arr,(2,2))

array([[27, 36],
       [19, 17]], dtype=int32)

In [37]:
arr.T

array([[27, 17, 14],
       [36, 36, 45],
       [19, 36, 24]], dtype=int32)

In [38]:
arr

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [39]:
arr>3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
arr

array([[27, 36, 19],
       [17, 36, 36],
       [14, 45, 24]], dtype=int32)

In [41]:
arr[[2,1],[1]]

array([45, 36], dtype=int32)

In [42]:
arr[1:,2]

array([36, 24], dtype=int32)

In [43]:
np.sort(arr)

array([[19, 27, 36],
       [17, 36, 36],
       [14, 24, 45]], dtype=int32)

In [44]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Sorting (returns a copy by default)
print(np.sort(arr))
# [1 1 2 3 4 5 6 9]

# Indices that would sort the original array
idx = np.argsort(arr)
print(idx)  # use arr[idx] to get sorted values

# Searchsorted: insert positions to keep order (binary search on sorted data)
sorted_arr = np.array([1, 3, 5, 7, 9])
positions = np.searchsorted(sorted_arr, [2, 4, 8])
print(positions)  # where each value would be inserted

# Counting: nonzero elements matching a condition
mask = arr > 4
print(np.count_nonzero(mask))
print(np.sum(mask))  # same for boolean arrays

# Unique values and counts
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

# Logical combinations (element-wise)
a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a, b))
print(np.logical_or(a, b))

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
[1 2 4]
3
3
[1 2 3 4 5 6 9] [2 1 1 1 1 1 1]
[False False  True]
[ True False  True]


In [45]:
sorted_arr = np.array([1, 3, 5, 7, 9])
positions = np.searchsorted(sorted_arr, [2, 4, 8])
print(positions)

[1 2 4]


In [46]:
np.power(arr,4)

array([  81,    1,  256,    1,  625, 6561,   16, 1296])

In [47]:
np.exp(arr)

array([2.00855369e+01, 2.71828183e+00, 5.45981500e+01, 2.71828183e+00,
       1.48413159e+02, 8.10308393e+03, 7.38905610e+00, 4.03428793e+02])

In [48]:
np.log(arr)

array([1.09861229, 0.        , 1.38629436, 0.        , 1.60943791,
       2.19722458, 0.69314718, 1.79175947])

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [50]:
np.percentile(arr,[25,50,75])

array([3.25, 5.5 , 7.75])

In [51]:
a= np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [52]:
c= np.dot(a,b)

In [53]:
c

array([[19, 22],
       [43, 50]])

In [54]:
np.cross(a,b)

C:\Users\PL\AppData\Local\Temp\ipykernel_21908\3739438254.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([-4, -4])

In [55]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [56]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
b

array([[5, 6],
       [7, 8]])

In [58]:
np.concatenate([a,b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [59]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])


In [71]:
np.vsplit(arr,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [68]:
feature1 = np.random.randint(0,10,5)
feature2 = np.random.randint(0,10, 5)

In [70]:
x = np.vstack([feature1, feature2])
x

array([[0, 5, 3, 1, 8],
       [2, 4, 4, 7, 6]], dtype=int32)

In [72]:
arr = np.random.randint(1,100,(5,5))

In [73]:
arr

array([[49, 45, 83, 61, 24],
       [92, 68, 57, 68, 73],
       [43,  1, 97, 79, 47],
       [38, 95, 82, 82, 98],
       [29, 18, 31, 38, 56]], dtype=int32)

In [76]:
print(arr.mean())
print(arr.max())
print(arr.min())

58.16
98
1


In [81]:
arr = np.arange(1,21)

In [83]:
even = arr[arr%2==0]
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [84]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

C = A @ B
det = np.linalg.det(C)
print("Determinant:", det)

Determinant: 0.015831771491378772


In [85]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [88]:
arr= np.concatenate([arr1,arr2],axis=0)

In [87]:
np.concatenate([arr1,arr2],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [89]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [90]:
np.vsplit(arr,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [92]:
np.hsplit(arr,2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [93]:
data = np.array([10, 20, 30, 40, 50])
normalization = (data-data.min())/(data.max()-data.min())

In [94]:
normalization

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [97]:
standard = (data-data.mean())/data.std()

In [98]:
standard

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])