In [1]:
import numpy as np

print(np.__version__)

2.1.3


In [2]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
# Output: [1 2 3 4 5]

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)  # Output: (2, 2, 2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
zeros= np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
full = np.full((2,3),'Shape of you')
full

array([['Shape of you', 'Shape of you', 'Shape of you'],
       ['Shape of you', 'Shape of you', 'Shape of you']], dtype='<U12')

In [6]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
linespace = np.linspace(-10,10,5)
print(linespace)

[-10.  -5.   0.   5.  10.]


In [8]:
arange = np.arange(13)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
random = np.random.rand(3,4)
random

array([[0.74171621, 0.71782623, 0.65164038, 0.76845275],
       [0.88437662, 0.88412342, 0.89611029, 0.6408804 ],
       [0.6932757 , 0.11457768, 0.94284039, 0.18090597]])

In [13]:
randint = np.random.randint(0,50,(3,3))
randint

array([[15, 47, 46],
       [ 3,  7, 33],
       [29, 19, 39]], dtype=int32)

In [20]:
nrmal = np.random.normal(10,5,(3,3))
nrmal

array([[10.20662147,  8.96478825, -1.9832611 ],
       [ 5.2194242 , 11.07762107, 14.3623494 ],
       [ 4.55450076,  2.64656361, 16.17735471]])

In [21]:
arr=randint

In [22]:
arr

array([[15, 47, 46],
       [ 3,  7, 33],
       [29, 19, 39]], dtype=int32)

In [23]:
arr.shape

(3, 3)

In [24]:
arr.size

9

In [25]:
arr.ndim

2

In [33]:
arr.dtype

dtype('int32')

In [36]:
arr.nbytes

36

In [38]:
arr.sum()

np.int64(238)

In [39]:
arr.mean()

np.float64(26.444444444444443)

In [40]:
arr.std()

np.float64(15.370325747369407)

In [43]:
arr.min()

np.int32(3)

In [46]:
arr.var()

np.float64(236.2469135802469)

In [48]:
arr.max()

np.int32(47)

In [49]:
arr.argmax()

np.int64(1)

In [51]:
arr.argmin()

np.int64(3)

In [52]:
arr.sum(axis=1)

array([108,  43,  87])

In [54]:
arr.sum(axis=0)

array([ 47,  73, 118])