In [1]:
import numpy as np

print(np.__version__)

2.1.3


In [2]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)
# Output: [1 2 3 4 5]

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)  # Output: (2, 2, 2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
zeros= np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
full = np.full((2,3),'Shape of you')
full

array([['Shape of you', 'Shape of you', 'Shape of you'],
       ['Shape of you', 'Shape of you', 'Shape of you']], dtype='<U12')

In [6]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
linespace = np.linspace(-10,10,5)
print(linespace)

[-10.  -5.   0.   5.  10.]


In [8]:
arange = np.arange(13)
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
random = np.random.rand(3,4)
random

array([[0.21575902, 0.55630168, 0.89537822, 0.65987077],
       [0.28640665, 0.33771326, 0.03842937, 0.47609323],
       [0.01946009, 0.92511603, 0.81589701, 0.60832085]])

In [10]:
randint = np.random.randint(0,50,(3,3))
randint

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [11]:
nrmal = np.random.normal(10,5,(3,3))
nrmal

array([[ 1.29737122,  7.66347853, -2.51449535],
       [12.78704192,  6.35204921, 12.62870891],
       [12.50565644, 10.25392766,  6.91052325]])

In [12]:
arr=randint

In [13]:
arr

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [14]:
arr.shape

(3, 3)

In [15]:
arr.size

9

In [16]:
arr.ndim

2

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr.nbytes

36

In [19]:
arr.sum()

np.int64(149)

In [20]:
arr.mean()

np.float64(16.555555555555557)

In [21]:
arr.std()

np.float64(10.62608019200465)

In [22]:
arr.min()

np.int32(0)

In [23]:
arr.var()

np.float64(112.91358024691358)

In [24]:
arr.max()

np.int32(38)

In [25]:
arr.argmax()

np.int64(3)

In [26]:
arr.argmin()

np.int64(0)

In [27]:
arr.sum(axis=1)

array([31, 77, 41])

In [28]:
arr.sum(axis=0)

array([56, 31, 62])

In [29]:
arr

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [30]:
np.arange(12).reshape(3,4)
np.arange(12).reshape(3,4).shape

(3, 4)

In [31]:
arr

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [32]:
arr.ravel()

array([ 0,  7, 24, 38, 14, 25, 18, 10, 13], dtype=int32)

In [33]:
arr.flatten()

array([ 0,  7, 24, 38, 14, 25, 18, 10, 13], dtype=int32)

In [34]:
arr1 = np.array([1, 2, 3, 4])

In [35]:
np.resize(arr,(2,2))

array([[ 0,  7],
       [24, 38]], dtype=int32)

In [36]:
arr.T

array([[ 0, 38, 18],
       [ 7, 14, 10],
       [24, 25, 13]], dtype=int32)

In [37]:
arr

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [38]:
arr>3

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
arr

array([[ 0,  7, 24],
       [38, 14, 25],
       [18, 10, 13]], dtype=int32)

In [40]:
arr[[2,1],[1]]

array([10, 14], dtype=int32)

In [41]:
arr[1:,2]

array([25, 13], dtype=int32)

In [42]:
np.sort(arr)

array([[ 0,  7, 24],
       [14, 25, 38],
       [10, 13, 18]], dtype=int32)

In [43]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Sorting (returns a copy by default)
print(np.sort(arr))
# [1 1 2 3 4 5 6 9]

# Indices that would sort the original array
idx = np.argsort(arr)
print(idx)  # use arr[idx] to get sorted values

# Searchsorted: insert positions to keep order (binary search on sorted data)
sorted_arr = np.array([1, 3, 5, 7, 9])
positions = np.searchsorted(sorted_arr, [2, 4, 8])
print(positions)  # where each value would be inserted

# Counting: nonzero elements matching a condition
mask = arr > 4
print(np.count_nonzero(mask))
print(np.sum(mask))  # same for boolean arrays

# Unique values and counts
values, counts = np.unique(arr, return_counts=True)
print(values, counts)

# Logical combinations (element-wise)
a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a, b))
print(np.logical_or(a, b))

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
[1 2 4]
3
3
[1 2 3 4 5 6 9] [2 1 1 1 1 1 1]
[False False  True]
[ True False  True]


In [44]:
sorted_arr = np.array([1, 3, 5, 7, 9])
positions = np.searchsorted(sorted_arr, [2, 4, 8])
print(positions)

[1 2 4]


In [45]:
np.power(arr,4)

array([  81,    1,  256,    1,  625, 6561,   16, 1296])

In [46]:
np.exp(arr)

array([2.00855369e+01, 2.71828183e+00, 5.45981500e+01, 2.71828183e+00,
       1.48413159e+02, 8.10308393e+03, 7.38905610e+00, 4.03428793e+02])

In [47]:
np.log(arr)

array([1.09861229, 0.        , 1.38629436, 0.        , 1.60943791,
       2.19722458, 0.69314718, 1.79175947])

In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [49]:
np.percentile(arr,[25,50,75])

array([3.25, 5.5 , 7.75])

In [50]:
a= np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [51]:
c= np.dot(a,b)

In [52]:
c

array([[19, 22],
       [43, 50]])

In [53]:
np.cross(a,b)

C:\Users\PL\AppData\Local\Temp\ipykernel_18044\3739438254.py:1: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([-4, -4])

In [54]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [55]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
b

array([[5, 6],
       [7, 8]])

In [57]:
np.concatenate([a,b],axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [58]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
