# Numpy 


In [179]:
#python and numpy speedtest

#pythonic way
import numpy as np
import time

size = 1000000

py_data = list(range(size))
py_start = time.time()
py_result = [ x * 1.10 for x in py_data]
py_time = time.time()- py_start


#numpy way

np_array = np.arange(size, dtype = float)
np_start = time.time()
np_result = np_array * 1.10
np_time = time.time()- np_start


print(f" Python time {py_time:.2f}")
print(f" Numpy time {np_time:.2f}")
print(f" Numpy faster {(py_time/np_time):.1f}x Times")

 Python time 0.09
 Numpy time 0.00
 Numpy faster 25.0x Times


## Creating Numpy Array

In [180]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [181]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [182]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [183]:
arange = np.arange(1,15)
arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [184]:
linespace  = np.linspace(-10,10,20, dtype= int)
linespace

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,  10])

In [185]:
import random

random = np.random.random((3,3))
random = np.round(random , 2)
random

array([[0.09, 0.96, 0.42],
       [0.16, 0.36, 0.02],
       [0.03, 0.28, 0.88]])

In [186]:
full = np.full((3,3),'Data Scientist')
full

array([['Data Scientist', 'Data Scientist', 'Data Scientist'],
       ['Data Scientist', 'Data Scientist', 'Data Scientist'],
       ['Data Scientist', 'Data Scientist', 'Data Scientist']],
      dtype='<U14')

In [187]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [188]:
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [189]:
nan = np.full((2,3),np.nan)
nan=np.empty(3)
nan.fill(np.nan)
nan


array([nan, nan, nan])

In [190]:
randint = np.random.randint(1,10,3)
randint

array([3, 6, 6], dtype=int32)

In [191]:
reshape =  np.arange(16).reshape(4,4)
reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Sales Data Array Creation

In [192]:
sales = np.array([100,234,345,126,400,133])

print("Array" , sales)
print("Array Data Type" , type(sales))
print('Array element data type' , sales.dtype)


Array [100 234 345 126 400 133]
Array Data Type <class 'numpy.ndarray'>
Array element data type int64


In [193]:
sales_2d = np.random.randint(3500,6500,16,dtype= int).reshape(4,4)

print(" 4 Region x 4 Month")
print(sales_2d)
print("shape",sales_2d.shape)

 4 Region x 4 Month
[[3698 4192 3996 4137]
 [4698 3737 5157 6201]
 [3713 3672 5587 3875]
 [3563 4146 3800 3536]]
shape (4, 4)


In [194]:
zeros = np.zeros(5)           # [0. 0. 0. 0. 0.]
ones  = np.ones((2, 3))       # 2×3 matrix of 1s
full  = np.full((3, 3), 7)    # 3×3 matrix filled with 7
eye   = np.eye(3)             # 3×3 identity matrix

print("zeros:", zeros)
print("ones:\n", ones)
print("full (7s):\n", full)
print("identity:\n", eye)

zeros: [0. 0. 0. 0. 0.]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full (7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



#### Mini Excercise

1. Create an array of all months' numbers (1 to 12) using `np.arange`
2. Create a 3×4 matrix of zeros (3 rows, 4 columns) representing a blank sales table
3. Create an array of 5 evenly spaced values between 0 and 1 (like probability thresholds)

```python
# Your answers here:
months = ?
blank_table = ?
thresholds = ?
```

In [195]:
months = np.arange (1,13)
months

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [196]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [197]:
evenly = np.linspace(0,1,5)
evenly

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### One shot

In [198]:
import numpy as np

arrays = {
    "arange": np.arange(15),
    "ones": np.ones((3, 3)),
    "zeros": np.zeros((3, 3)),
    "random": np.random.random((3, 3)),
    "randint": np.random.randint(1, 10, 25).reshape(5, 5),
    "eye": np.eye(4),
    "fill": np.full((1, 2), "Eid Mubarak"),
    "empty": np.empty((3, 3)),
    "linspace": np.linspace(-10, 10, 10, dtype=int)
}


for i , (name, arr) in enumerate(arrays.items(),1):
    print(f" {i}.{name} : \n\n {arr}\n")

 1.arange : 

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 2.ones : 

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 3.zeros : 

 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 4.random : 

 [[0.89327757 0.93746456 0.696884  ]
 [0.35767643 0.92218977 0.54279887]
 [0.78186103 0.03243044 0.39091894]]

 5.randint : 

 [[3 9 8 8 1]
 [4 6 6 4 6]
 [1 9 7 8 1]
 [2 8 2 9 7]
 [7 7 1 5 8]]

 6.eye : 

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 7.fill : 

 [['Eid Mubarak' 'Eid Mubarak']]

 8.empty : 

 [[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23046484e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307 3.62651150e-317]]

 9.linspace : 

 [-10  -8  -6  -4  -2   1   3   5   7  10]



## Array Attributes

In [199]:
df = np.random.randint(100, 1000, size=(12, 5, 3))
df

array([[[351, 689, 799],
        [359, 253, 572],
        [687, 108, 427],
        [118, 505, 991],
        [576, 572, 344]],

       [[250, 910, 463],
        [527, 275, 166],
        [414, 267, 466],
        [933, 580, 339],
        [333, 435, 503]],

       [[882, 830, 297],
        [985, 543, 925],
        [581, 671, 597],
        [359, 155, 924],
        [303, 575, 265]],

       [[628, 352, 257],
        [685, 968, 238],
        [593, 885, 689],
        [726, 383, 871],
        [233, 594, 150]],

       [[438, 949, 832],
        [715, 794, 728],
        [232, 418, 829],
        [182, 809, 947],
        [127, 315, 269]],

       [[148, 359, 951],
        [584, 668, 226],
        [365, 819, 584],
        [289, 423, 589],
        [903, 504, 646]],

       [[578, 258, 308],
        [950, 832, 128],
        [586, 150, 366],
        [616, 115, 881],
        [524, 798, 398]],

       [[468, 921, 377],
        [754, 704, 149],
        [564, 514, 826],
        [370, 454, 887],
        [65

In [200]:
df.shape

(12, 5, 3)

In [201]:
df.ndim

3

In [202]:
df.size

180

In [203]:
df.dtype

dtype('int32')

In [204]:
df.itemsize

4

### Section 4 — Indexing & Slicing

#### 4.1 The Mental Model

Think of indexing like **navigating a spreadsheet**:
- `array[row, column]` — pick one cell
- `array[start:stop]` — pick a range (stop is EXCLUDED)
- `array[::step]` — pick every nth element

#### 4.2 1D Indexing

In [205]:
temp = np.arange(16)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [206]:
temp[1:5:2]

array([1, 3])

In [207]:
temp = np.arange(16)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [208]:
# Single element access
print("Day 1 temp (index 0) :", temp[0])    # 22
print("Day 7 temp (index 6) :", temp[6])    # 40
print("Last day (index -1)  :", temp[-1])   # 30  ← negative indexing!
print("2nd to last (index-2):", temp[-2])   # 23
print()

# Slicing: array[start : stop : step]  (stop is NOT included)
print("First 3 days:", temp[0:3])     # [22 19 35]
print("Days 4-7:     ", temp[3:7])    # [28 31 17 40]
print("Last 3 days:  ", temp[-3:])    # [26 23 30]
print("Every 2nd day:", temp[::2])    # [22 35 31 40 23]
print("Reversed:      ", temp[::-1])

Day 1 temp (index 0) : 0
Day 7 temp (index 6) : 6
Last day (index -1)  : 15
2nd to last (index-2): 14

First 3 days: [0 1 2]
Days 4-7:      [3 4 5 6]
Last 3 days:   [13 14 15]
Every 2nd day: [ 0  2  4  6  8 10 12 14]
Reversed:       [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [209]:
#              Jan    Feb    Mar
sales = np.array([
    [5000, 4800, 5200],   # Row 0: North
    [3200, 3500, 3100],   # Row 1: South
    [4100, 3900, 4400],   # Row 2: East
    [6200, 5800, 6100],  # Row 3: West
])
sales

array([[5000, 4800, 5200],
       [3200, 3500, 3100],
       [4100, 3900, 4400],
       [6200, 5800, 6100]])

In [210]:
sales[1:3,2]

array([3100, 4400])

In [211]:
print(" Jan north sales : " , sales[0,0] )

 Jan north sales :  5000


In [212]:
print('March west sales :' , sales[3,2])

March west sales : 6100


In [213]:
sales = np.array([
    [5000, 4800, 5200],   # Row 0: North
    [3200, 3500, 3100],   # Row 1: South
    [4100, 3900, 4400],   # Row 2: East
    [6200, 5800, 6100],  # Row 3: West
])
sales

array([[5000, 4800, 5200],
       [3200, 3500, 3100],
       [4100, 3900, 4400],
       [6200, 5800, 6100]])

In [214]:
north_east = sales[[0,2],[1,2]] # arr[[row list] , [ colomn list]]

In [215]:
north_east

array([4800, 4400])

In [216]:
orginal = np.arange(15)
copy = orginal[1:5].copy()

In [217]:
copy

array([1, 2, 3, 4])

In [218]:
orginal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Section 5 — Boolean Indexing & Filtering

#### 5.1 Why Boolean Indexing Is Your Best Tool

In Excel, you use **filters** to show only rows matching a condition. In NumPy, that's boolean indexing — it's faster and more powerful.

The idea:
1. Create a **boolean mask** (array of True/False)
2. Use that mask to **select elements** where True

In [219]:
daily_sales = np.array([320, 450, 380, 290, 510, 620, 480])
target = 350

print("sales more than 400 :" ,daily_sales>target )

sales more than 400 : [False  True  True False  True  True  True]


In [220]:
target_done = daily_sales>350
print(target_done)
target_done.sum()

[False  True  True False  True  True  True]


np.int64(5)

In [221]:
# & and | or ~ not

ages = np.array([34, 67, 23, 45, 78, 56, 12, 89, 43, 61])


working_age = (ages >= 30) & (ages <= 65)
print("Working age patients:", ages[working_age])


Working age patients: [34 45 56 43 61]


In [222]:
# ── np.where() — the vectorized if/else ────────────────────────────────
# np.where(condition, value_if_true, value_if_false)

In [223]:
num =   np.arange(35,45)
grades

NameError: name 'grades' is not defined

In [ ]:
grades = np.where(num<40 , "Fail",num)
grades

array(['Fail', 'Fail', 'Fail', 'Fail', 'Fail', '40', '41', '42', '43',
       '44'], dtype='<U21')

In [ ]:
sales = np.array([8000, 12000, 9500, 15000, 7000, 11000])
bonus = np.where(sales>10000, 500 , 0)

print("Total payment " , sales + bonus)

Total payment  [ 8000 12500  9500 15500  7000 11500]


In [ ]:
#isin() count if 

categories = np.array(['A', 'B', 'C', 'A', 'D', 'B', 'E', 'C'])
premium_categories = ['A', 'C']

is_premium  = np.isin(categories ,premium_categories)
print("premium mask " , len(categories[is_premium]))
                    


premium mask  4


In [ ]:
import numpy as np

In [ ]:
prices = np.array([100, 250, 80, 340, 150])

In [ ]:
after_tax = prices * 1.15
after_discount = prices * 0.90




In [226]:
# universal Function
data = np.random.randint(1,100,15)
data

array([44, 14, 35, 13, 30, 37,  6,  6, 53, 40, 73, 58, 74, 37, 25],
      dtype=int32)

In [227]:
print("square root " , np.sqrt(data))

square root  [6.63324958 3.74165739 5.91607978 3.60555128 5.47722558 6.08276253
 2.44948974 2.44948974 7.28010989 6.32455532 8.54400375 7.61577311
 8.60232527 6.08276253 5.        ]


In [228]:
print("Absolute value" , np.abs(data))

Absolute value [44 14 35 13 30 37  6  6 53 40 73 58 74 37 25]


In [229]:
print("Power of two " , np.power(data,2))

Power of two  [1936  196 1225  169  900 1369   36   36 2809 1600 5329 3364 5476 1369
  625]


In [230]:
vals = np.array([1.234, 5.678, 9.012, 3.456])

print("Round 2" , np.round(vals , 1))

Round 2 [1.2 5.7 9.  3.5]


In [231]:
revenue = np.array([45000, 52000, 48000, 61000, 55000, 70000,
                    68000, 72000, 63000, 58000, 49000, 75000])

In [234]:
print("Revenue analysis")

info = {
    
    'Total Revenue' : f'{np.sum(revenue):.2f}',
    'Monthly Average': f"{np.mean(revenue):.2f}",
    'Monthly Average': f"{np.mean(revenue):.2f}",
    'Monthly Median': f"{np.median(revenue):.2f}",
    'Best Month': f"{np.max(revenue):.2f}", 
    'worst Month': f"{np.min(revenue):.2f}",
    'Std': f"{np.std(revenue):.2f}",
    'variance ': f"{np.var(revenue):.2f}"
    
}

for i ,(key , value ) in enumerate(info.items() , 1):
    print(f"{i}. {key} : {value}")

Revenue analysis
1. Total Revenue : 716000.00
2. Monthly Average : 59666.67
3. Monthly Median : 59500.00
4. Best Month : 75000.00
5. worst Month : 45000.00
6. Std : 9681.02
7. variance  : 93722222.22


In [235]:
#pecentaile 
customer_spending = np.array([120, 340, 85, 210, 450, 90, 175, 620,
                               310, 55, 280, 190, 780, 145, 230])


In [237]:
p25 = np.percentile(customer_spending,25)
p25

np.float64(132.5)

In [238]:
p50 = np.percentile(customer_spending, 50)
print(p50)

print(np.median(customer_spending))

210.0
210.0


In [240]:
scores = np.array([78, 45, 92, 61, 88, 34, 75, 95, 51, 67])

sort_asc = np.sort(scores)
sort_des = np.sort(scores)[::-1]

print(sort_asc)
print(sort_des)

[34 45 51 61 67 75 78 88 92 95]
[95 92 88 78 75 67 61 51 45 34]


In [246]:
ranking= np.argsort(scores)[::-1]
print(ranking)

[7 2 4 0 6 9 3 8 1 5]


In [247]:
top_3 = ranking[:3]
print(top_3)

[7 2 4]


In [248]:
# finding min max position use argmin , argmax

max = np.argmax(scores)

In [249]:
max

np.int64(7)

In [250]:
monthly_sales = np.array([45000, 52000, 48000, 61000, 55000, 70000,
                           68000, 72000, 63000, 58000, 49000, 75000])
months = ['Jan','Feb','Mar','Apr','May','Jun',
          'Jul','Aug','Sep','Oct','Nov','Dec']

In [252]:
best_month_idx = np.argmax(monthly_sales)
worst_month_idx = np.argmin(monthly_sales)

best_month_idx

np.int64(11)

In [253]:
print(f" best month {months[best_month_idx]} : {monthly_sales[best_month_idx]}")

 best month Dec : 75000


In [254]:
visit_hours = np.array([9, 14, 9, 22, 14, 9, 14, 3, 19, 22, 14, 9])

In [255]:
unique_hour , counts  = np.unique(visit_hours , return_counts= True)

In [256]:
unique_hour

array([ 3,  9, 14, 19, 22])

In [257]:
counts

array([1, 4, 4, 1, 2])

In [258]:
ratings = np.array([8, 15, -2, 7, 10, 0, 6, 11, 9, 3])

In [260]:
valid_rating = np.clip(ratings , 1,10)
valid_rating

array([ 8, 10,  1,  7, 10,  1,  6, 10,  9,  3])

In [262]:
seed = np.random.seed(10)
print(seed)

None


In [263]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

flat1 = matrix.flatten()
flat2 = matrix.ravel()

print(flat1)
print(flat2)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [264]:
jan = np.array([5000, 3200, 4100, 6200])  # 4 regions, January
feb = np.array([4800, 3500, 3900, 5800])  # 4 regions, February
mar = np.array([5200, 3100, 4400, 6100])  # 4 regions, March

In [266]:
month_as_rows = np.vstack([jan,feb,mar])
month_as_rows

array([[5000, 3200, 4100, 6200],
       [4800, 3500, 3900, 5800],
       [5200, 3100, 4400, 6100]])

In [267]:

month_as_column = np.hstack([jan , feb ,mar])

In [268]:
month_as_column

array([5000, 3200, 4100, 6200, 4800, 3500, 3900, 5800, 5200, 3100, 4400,
       6100])