In [1]:
import numpy as np


In [7]:
a1 = np.arange(12)
a2=np.arange(12).reshape(3,4)
a1
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.max(a2,axis=1)

array([ 3,  7, 11])

In [13]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [14]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a2[:2,1:3]

array([[1, 2],
       [5, 6]])