In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7])

In [3]:
print(array)

[1 2 3 4 5 6 7]


In [5]:
float_array = np.array([1,2,3] , dtype=float)
print(float_array)

[1. 2. 3.]


In [7]:
range_arr = np.arange(1,10)
print(range_arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
nd_array = np.arange(1,13).reshape(3,4)#row , column
print(nd_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
ones= np.ones((4,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
random = np.random.random((1,25))
print(random)

[[0.7299879  0.41741472 0.9986067  0.61869455 0.66216686 0.22793894
  0.69425639 0.47901753 0.6820144  0.65150247 0.78286348 0.96388634
  0.75060908 0.3136044  0.90375207 0.50132747 0.33762084 0.64082053
  0.6283916  0.54842023 0.26144342 0.6806166  0.51005058 0.72085724
  0.57716592]]


In [18]:
linearspace = np.linspace(-10,10,20,dtype=int)
print(linearspace)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8  10]


In [19]:
np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])