# 📚 Complete NumPy Study Notes for Data Analysts
### From Zero to Confident — Everything You Need

---

> **How to use this notebook:**
> - Read every explanation carefully before running the code
> - **Run every code cell yourself** — don't just read output
> - Look for 💡 **Analyst Insight** boxes — these connect NumPy to real data work
> - Look for ⚠️ **Common Mistake** boxes — these save you hours of debugging
> - At the end of each section, there's a mini-exercise to test yourself

---

## 📋 Table of Contents

| # | Topic | Difficulty |
|---|-------|------------|
| 1 | What is NumPy & Why It Matters | 🟢 |
| 2 | Creating Arrays | 🟢 |
| 3 | Array Attributes | 🟢 |
| 4 | Indexing & Slicing | 🟢 |
| 5 | Boolean Indexing & Filtering | 🟢 |
| 6 | Math & Arithmetic Operations | 🟢 |
| 7 | Statistical Functions | 🟡 |
| 8 | Sorting & Searching | 🟡 |
| 9 | Reshaping & Stacking Arrays | 🟡 |
| 10 | Broadcasting | 🟡 |
| 11 | Random Number Generation | 🟡 |
| 12 | Handling Missing Data (NaN) | 🟡 |
| 13 | Vectorization vs Loops | 🟡 |
| 14 | Advanced Statistics | 🔴 |
| 15 | Linear Algebra Basics | 🔴 |
| 16 | Simulation & Monte Carlo | 🔴 |
| 17 | Putting It All Together | 🔴 |

---

## Section 1 — What is NumPy & Why It Matters

### 1.1 The Problem NumPy Solves

Imagine you work at a company. Your manager gives you a list of **1 million customer purchase amounts** and says:

> *"Add 10% tax to every purchase amount."*

With plain Python, you would write a loop:

```python
# Plain Python way — SLOW
result = []
for amount in purchases:
    result.append(amount * 1.10)
```

With NumPy:

```python
# NumPy way — FAST and CLEAN
result = purchases * 1.10
```

NumPy is **up to 100x faster** than plain Python loops for numerical work, because it:
- Stores data in **contiguous memory** (like a C array)
- Performs operations in **compiled C code under the hood**
- Operates on **entire arrays at once** (vectorization)

### 1.2 NumPy in the Data Analyst Stack

```
NumPy  →  the foundation (arrays, math, stats)
  ↓
Pandas →  built on NumPy (DataFrames = NumPy arrays with labels)
  ↓
Scikit-learn, TensorFlow, etc. → all use NumPy arrays internally
```

**Understanding NumPy = understanding the language every data tool speaks.**

In [2]:
# Always start by importing NumPy
# 'np' is the universal alias — everyone uses it
import numpy as np

# Check your NumPy version
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [3]:
# Speed comparison: Python list vs NumPy array
import time

size = 1_000_000

# Python list approach
py_list = list(range(size))
start = time.time()
result_py = [x * 1.10 for x in py_list]
py_time = time.time() - start

# NumPy approach
np_array = np.arange(size, dtype=float)
start = time.time()
result_np = np_array * 1.10
np_time = time.time() - start

print(f"Python loop time : {py_time:.4f} seconds")
print(f"NumPy time       : {np_time:.4f} seconds")
print(f"NumPy is {py_time/np_time:.1f}x faster!")

Python loop time : 0.0777 seconds
NumPy time       : 0.0028 seconds
NumPy is 27.8x faster!


---
## Section 2 — Creating Arrays

### 2.1 The ndarray — NumPy's Core Object

Everything in NumPy is an **ndarray** (N-dimensional array). Think of it as a supercharged list that:
- Can be 1D, 2D, 3D, or more
- Stores only **one data type** (all integers, all floats, etc.)
- Supports fast math operations on the whole array

### 2.2 Ways to Create Arrays

| Method | Use Case | Example |
|--------|----------|---------|
| `np.array()` | From existing Python list | `np.array([1,2,3])` |
| `np.zeros()` | Initialize with zeros | Blank templates |
| `np.ones()` | Initialize with ones | Weight matrices |
| `np.arange()` | Like Python range() | Sequences, indices |
| `np.linspace()` | Evenly spaced values | Plot axes, simulations |
| `np.random.*` | Random data | Simulations, testing |
| `np.full()` | Fill with one value | Constants |
| `np.eye()` | Identity matrix | Linear algebra |

In [4]:
# ── METHOD 1: From a Python list ──────────────────────────────────────────
# Use this when you already have data

# 1D array (like a single column of data)
sales = np.array([320, 450, 380, 290, 510, 620, 480])
print("1D array:", sales)
print("Type:", type(sales))        # <class 'numpy.ndarray'>
print("Data type:", sales.dtype)   # int64 — NumPy chose integer automatically
print()

1D array: [320 450 380 290 510 620 480]
Type: <class 'numpy.ndarray'>
Data type: int64



In [5]:
# 2D array (like a table: rows and columns)
#                Jan    Feb    Mar
sales_2d = np.array([
    [5000, 4800, 5200],   # Row 0: North region
    [3200, 3500, 3100],   # Row 1: South region
    [4100, 3900, 4400],   # Row 2: East  region
    [6200, 5800, 6100],   # Row 3: West  region
])

print("2D array (4 regions × 3 months):")
print(sales_2d)
print("Shape:", sales_2d.shape)    # (4, 3) → 4 rows, 3 columns
print()

2D array (4 regions × 3 months):
[[5000 4800 5200]
 [3200 3500 3100]
 [4100 3900 4400]
 [6200 5800 6100]]
Shape: (4, 3)



In [6]:
# ── METHOD 2: Special arrays ───────────────────────────────────────────────

zeros = np.zeros(5)           # [0. 0. 0. 0. 0.]
ones  = np.ones((2, 3))       # 2×3 matrix of 1s
full  = np.full((3, 3), 7)    # 3×3 matrix filled with 7
eye   = np.eye(3)             # 3×3 identity matrix

print("zeros:", zeros)
print("ones:\n", ones)
print("full (7s):\n", full)
print("identity:\n", eye)

zeros: [0. 0. 0. 0. 0.]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
full (7s):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# ── METHOD 3: Sequences ───────────────────────────────────────────────────

# np.arange(start, stop, step)  — stop is EXCLUSIVE
days     = np.arange(1, 8)          # [1 2 3 4 5 6 7]
evens    = np.arange(0, 20, 2)      # [0 2 4 6 8 10 12 14 16 18]
countdown = np.arange(10, 0, -1)    # [10 9 8 7 6 5 4 3 2 1]

print("Days of week:  ", days)
print("Even numbers:  ", evens)
print("Countdown:     ", countdown)
print()

# np.linspace(start, stop, num)  — stop IS included, gives exactly 'num' values
# 💡 Use linspace when you know HOW MANY points you want
# 💡 Use arange when you know the STEP SIZE

percentages = np.linspace(0, 100, 11)  # 0%, 10%, 20%, ..., 100%
print("Percentages:", percentages)

Days of week:   [1 2 3 4 5 6 7]
Even numbers:   [ 0  2  4  6  8 10 12 14 16 18]
Countdown:      [10  9  8  7  6  5  4  3  2  1]

Percentages: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [8]:
# ── DATA TYPES ─────────────────────────────────────────────────────────────
# NumPy picks the dtype automatically, but you can specify it

prices_int   = np.array([10, 20, 30])            # int64 by default
prices_float = np.array([10, 20, 30], dtype=float)  # force float64
flags        = np.array([True, False, True])       # bool

print("int array  :", prices_int,   "dtype:", prices_int.dtype)
print("float array:", prices_float, "dtype:", prices_float.dtype)
print("bool array :", flags,        "dtype:", flags.dtype)

# ⚠️ COMMON MISTAKE: Mixing types in a list
# NumPy will 'upcast' everything to the broadest type
mixed = np.array([1, 2.5, 3])   # All become float!
print("\nMixed [1, 2.5, 3] becomes:", mixed, "dtype:", mixed.dtype)

int array  : [10 20 30] dtype: int64
float array: [10. 20. 30.] dtype: float64
bool array : [ True False  True] dtype: bool

Mixed [1, 2.5, 3] becomes: [1.  2.5 3. ] dtype: float64


### ✏️ Mini Exercise 2
1. Create an array of all months' numbers (1 to 12) using `np.arange`
2. Create a 3×4 matrix of zeros (3 rows, 4 columns) representing a blank sales table
3. Create an array of 5 evenly spaced values between 0 and 1 (like probability thresholds)

```python
# Your answers here:
months = ?
blank_table = ?
thresholds = ?
```

In [9]:
# Try Exercise 2 here:


---
## Section 3 — Array Attributes

Before you analyze data, you need to **understand its shape**. These are the first things a data analyst checks when they receive a new dataset.

| Attribute | What it tells you | Equivalent in Excel |
|-----------|-------------------|---------------------|
| `.shape` | (rows, columns) | =ROWS() and =COLUMNS() |
| `.ndim` | Number of dimensions | 1D=list, 2D=table |
| `.size` | Total number of elements | =COUNTA() on whole sheet |
| `.dtype` | Data type stored | Cell format (number, text) |
| `.itemsize` | Bytes per element | Memory info |

In [10]:
# Real-life example: You receive a dataset of monthly sales
# 12 months × 5 products × 3 regions = 3D array

dataset = np.random.randint(100, 1000, size=(12, 5, 3))

print("=== Understanding Your Dataset ===")
print(f"Shape     : {dataset.shape}    → (months, products, regions)")
print(f"Dimensions: {dataset.ndim}        → 3D array")
print(f"Total cells: {dataset.size}     → 12 × 5 × 3")
print(f"Data type : {dataset.dtype}     → integer values")
print(f"Memory    : {dataset.nbytes} bytes  → {dataset.nbytes/1024:.2f} KB")

=== Understanding Your Dataset ===
Shape     : (12, 5, 3)    → (months, products, regions)
Dimensions: 3        → 3D array
Total cells: 180     → 12 × 5 × 3
Data type : int32     → integer values
Memory    : 720 bytes  → 0.70 KB


In [11]:
# Common pattern: Check shape BEFORE every operation
# This is the #1 habit of good data analysts

a = np.array([1, 2, 3, 4, 6])          # 1D, shape (5,)
b = np.array([[1, 2], [3, 4], [5, 6]]) # 2D, shape (3, 2)

print("Array a shape:", a.shape)  # (5,) — 1D with 5 elements
print("Array b shape:", b.shape)  # (3, 2) — 3 rows, 2 columns

# 💡 ANALYST TIP: In shape (3, 2)
#   - First number (3) = rows = observations = records
#   - Second number (2) = columns = features = variables

Array a shape: (5,)
Array b shape: (3, 2)


---
## Section 4 — Indexing & Slicing

### 4.1 The Mental Model

Think of indexing like **navigating a spreadsheet**:
- `array[row, column]` — pick one cell
- `array[start:stop]` — pick a range (stop is EXCLUDED)
- `array[::step]` — pick every nth element

### 4.2 1D Indexing

In [12]:
# Real data: Daily temperatures for 10 days
temps = np.array([22, 19, 35, 28, 31, 17, 40, 26, 23, 30])
#  index:          0   1   2   3   4   5   6   7   8   9

print("Full array:", temps)
print()

# Single element access
print("Day 1 temp (index 0) :", temps[0])    # 22
print("Day 7 temp (index 6) :", temps[6])    # 40
print("Last day (index -1)  :", temps[-1])   # 30  ← negative indexing!
print("2nd to last (index-2):", temps[-2])   # 23
print()

# Slicing: array[start : stop : step]  (stop is NOT included)
print("First 3 days:", temps[0:3])     # [22 19 35]
print("Days 4-7:     ", temps[3:7])    # [28 31 17 40]
print("Last 3 days:  ", temps[-3:])    # [26 23 30]
print("Every 2nd day:", temps[::2])    # [22 35 31 40 23]
print("Reversed:      ", temps[::-1])  # [30 23 26 40 17 31 28 35 19 22]

Full array: [22 19 35 28 31 17 40 26 23 30]

Day 1 temp (index 0) : 22
Day 7 temp (index 6) : 40
Last day (index -1)  : 30
2nd to last (index-2): 23

First 3 days: [22 19 35]
Days 4-7:      [28 31 17 40]
Last 3 days:   [26 23 30]
Every 2nd day: [22 35 31 40 23]
Reversed:       [30 23 26 40 17 31 28 35 19 22]


In [13]:
# ── 2D INDEXING ─────────────────────────────────────────────────────────────
# Format: array[row_index, column_index]
#                  ↑            ↑
#               which row    which col

#              Jan    Feb    Mar
sales = np.array([
    [5000, 4800, 5200],   # Row 0: North
    [3200, 3500, 3100],   # Row 1: South
    [4100, 3900, 4400],   # Row 2: East
    [6200, 5800, 6100],   # Row 3: West
])

print("Full table:\n", sales)
print()
# Single cell
print("North Jan sales  :", sales[0, 0])    # 5000 → row 0, col 0
print("East  Feb sales  :", sales[2, 1])    # 3900 → row 2, col 1
print("West  Mar sales  :", sales[3, 2])    # 6100 → row 3, col 2
print()

# Entire row (one region, all months)
print("All North data   :", sales[0, :])    # [5000 4800 5200]
print("All West data    :", sales[3, :])    # [6200 5800 6100]
print()

# Entire column (all regions, one month)
print("Jan sales (all)  :", sales[:, 0])    # [5000 3200 4100 6200]
print("Feb sales (all)  :", sales[:, 1])    # [4800 3500 3900 5800]

Full table:
 [[5000 4800 5200]
 [3200 3500 3100]
 [4100 3900 4400]
 [6200 5800 6100]]

North Jan sales  : 5000
East  Feb sales  : 3900
West  Mar sales  : 6100

All North data   : [5000 4800 5200]
All West data    : [6200 5800 6100]

Jan sales (all)  : [5000 3200 4100 6200]
Feb sales (all)  : [4800 3500 3900 5800]


In [14]:
# ── FANCY INDEXING: Selecting multiple rows/cols at once ──────────────────

# Select rows 0 and 2 (North and East) — pass a LIST of indices
north_east = sales[[0, 2], :]
print("North & East sales:\n", north_east)
print()

# Select specific cells: (row 0, col 0) and (row 3, col 2)
specific = sales[[0, 3], [0, 2]]
print("North-Jan and West-Mar:", specific)  # [5000, 6100]
print()

# ⚠️ KEY DIFFERENCE:
# sales[0, 2]    → single element (scalar)
# sales[[0], [2]] → array with one element
# sales[0:2, :]  → rows 0 and 1 (slice)
# sales[[0,1],:] → rows 0 and 1 (fancy indexing, same result here)

North & East sales:
 [[5000 4800 5200]
 [4100 3900 4400]]

North-Jan and West-Mar: [5000 6100]



### ⚠️ IMPORTANT: Views vs Copies

This is one of the most common bugs in NumPy. When you slice an array, you get a **view** (a window into the original data). When you modify the view, you modify the original!


In [15]:
original = np.array([10, 20, 30, 40, 50])

# ❌ DANGEROUS: This is a VIEW, not a copy
view = original[1:4]       # [20 30 40]
view[0] = 999              # Modifies original!
print("Original after modifying view:", original)  # [10 999 30 40 50]

# ✅ SAFE: Use .copy() to make an independent copy
original2 = np.array([10, 20, 30, 40, 50])
copy = original2[1:4].copy()  # True copy
copy[0] = 999                  # Does NOT affect original
print("Original2 after modifying copy:", original2)  # [10 20 30 40 50]  ✓

# 💡 RULE: Always use .copy() when you want to modify sliced data
#          without affecting the source

Original after modifying view: [ 10 999  30  40  50]
Original2 after modifying copy: [10 20 30 40 50]


---
## Section 5 — Boolean Indexing & Filtering

### 5.1 Why Boolean Indexing Is Your Best Tool

In Excel, you use **filters** to show only rows matching a condition. In NumPy, that's boolean indexing — it's faster and more powerful.

The idea:
1. Create a **boolean mask** (array of True/False)
2. Use that mask to **select elements** where True

In [16]:
# Real scenario: Filter sales above target
daily_sales = np.array([320, 450, 380, 290, 510, 620, 480])
target = 400

# Step 1: Create the boolean mask
mask = daily_sales > target
print("Sales array :", daily_sales)
print("Mask (>400) :", mask)           # [False  True False False  True  True  True]
print()

# Step 2: Apply the mask to get matching values
above_target = daily_sales[mask]
print("Days above target:", above_target)        # [450 510 620 480]
print("Count of such days:", mask.sum())          # 4   ← True=1, False=0
print("Percentage:        ", mask.mean() * 100, "%")  # 57.1%

Sales array : [320 450 380 290 510 620 480]
Mask (>400) : [False  True False False  True  True  True]

Days above target: [450 510 620 480]
Count of such days: 4
Percentage:         57.14285714285714 %


In [17]:
# ── COMBINING CONDITIONS ─────────────────────────────────────────────────
# Use & (AND), | (OR), ~ (NOT) — NOT Python's 'and', 'or', 'not'!

ages = np.array([34, 67, 23, 45, 78, 56, 12, 89, 43, 61])

# Adults between 30 and 65
# ⚠️ MUST use parentheses around each condition when combining
working_age = (ages >= 30) & (ages <= 65)
print("Working age patients:", ages[working_age])

# Seniors OR children (outside working age)
not_working_age = (ages < 30) | (ages > 65)
print("Seniors or children :", ages[not_working_age])

# Invert a mask using ~
seniors = ages >= 60
non_seniors = ~seniors
print("Non-seniors         :", ages[non_seniors])

Working age patients: [34 45 56 43 61]
Seniors or children : [67 23 78 12 89]
Non-seniors         : [34 23 45 56 12 43]


In [18]:
# ── np.where() — the vectorized if/else ────────────────────────────────
# np.where(condition, value_if_true, value_if_false)
# This is like Excel's =IF() formula applied to entire arrays

scores = np.array([45, 78, 52, 91, 38, 65, 83, 47, 72, 56])

# Label each score as 'Pass' or 'Fail'
grades = np.where(scores >= 50, 'Pass', 'Fail')
print("Scores:", scores)
print("Grades:", grades)
print()

# Numeric np.where: give bonus 500 if sales > 10000, else 0
sales = np.array([8000, 12000, 9500, 15000, 7000, 11000])
bonus = np.where(sales > 10000, 500, 0)
print("Sales:", sales)
print("Bonus:", bonus)
print("Total payout:", sales + bonus)

Scores: [45 78 52 91 38 65 83 47 72 56]
Grades: ['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']

Sales: [ 8000 12000  9500 15000  7000 11000]
Bonus: [  0 500   0 500   0 500]
Total payout: [ 8000 12500  9500 15500  7000 11500]


In [19]:
# ── np.isin() — check membership ────────────────────────────────────────
# Like Excel's COUNTIF to check if values exist in a list

categories = np.array(['A', 'B', 'C', 'A', 'D', 'B', 'E', 'C'])
premium_categories = ['A', 'C']

is_premium = np.isin(categories, premium_categories)
print("All categories    :", categories)
print("Premium mask      :", is_premium)
print("Premium categories:", categories[is_premium])
print("Count premium     :", is_premium.sum())

All categories    : ['A' 'B' 'C' 'A' 'D' 'B' 'E' 'C']
Premium mask      : [ True False  True  True False False False  True]
Premium categories: ['A' 'C' 'A' 'C']
Count premium     : 4


---
## Section 6 — Math & Arithmetic Operations

### 6.1 Element-wise Operations

NumPy applies operations to **every element at once** — no loop needed. This is called **vectorization**.

In [20]:
prices = np.array([100, 250, 80, 340, 150])

# ── SCALAR OPERATIONS (array op number) ──────────────────────────────────
# Each element gets the same operation applied

after_tax     = prices * 1.15       # 15% tax on all
after_discount= prices * 0.80       # 20% off all
markup        = prices + 20         # $20 added to all
doubled       = prices * 2          # double all prices

print("Original :", prices)
print("+15% tax :", after_tax)
print("-20% disc:", after_discount)
print("+$20     :", markup)
print("×2       :", doubled)

Original : [100 250  80 340 150]
+15% tax : [115.  287.5  92.  391.  172.5]
-20% disc: [ 80. 200.  64. 272. 120.]
+$20     : [120 270 100 360 170]
×2       : [200 500 160 680 300]


In [21]:
# ── ELEMENT-WISE ARRAY OPERATIONS (array op array) ───────────────────────
# Both arrays must have the SAME shape (or be broadcastable — covered later)

revenue  = np.array([50000, 62000, 48000, 71000, 55000])
expenses = np.array([32000, 41000, 35000, 49000, 38000])

profit       = revenue - expenses
profit_margin= profit / revenue * 100     # percentage
total        = revenue + expenses

print("Revenue      :", revenue)
print("Expenses     :", expenses)
print("Profit       :", profit)
print("Margin (%)   :", np.round(profit_margin, 2))

# ⚠️ Shape mismatch causes ERROR:
# a = np.array([1, 2, 3])   shape (3,)
# b = np.array([1, 2])      shape (2,)
# a + b → ValueError!

Revenue      : [50000 62000 48000 71000 55000]
Expenses     : [32000 41000 35000 49000 38000]
Profit       : [18000 21000 13000 22000 17000]
Margin (%)   : [36.   33.87 27.08 30.99 30.91]


In [22]:
# ── UNIVERSAL FUNCTIONS (ufuncs) ─────────────────────────────────────────
# NumPy has math functions that work on entire arrays

data = np.array([4, 9, 16, 25, 36, 49, 64, 81, 100])

print("Original  :", data)
print("Square root:", np.sqrt(data))        # [2. 3. 4. 5. ...]
print("Log base e :", np.log(data).round(2))# natural log
print("Log base 10:", np.log10(data))       # log base 10
print("Absolute   :", np.abs(np.array([-3, -1, 0, 2, -5])))
print("Power of 2 :", np.power(data[:4], 2)) # square each
print()

# Rounding functions
vals = np.array([1.234, 5.678, 9.012, 3.456])
print("Original :", vals)
print("Round 2  :", np.round(vals, 2))
print("Floor    :", np.floor(vals))   # round DOWN
print("Ceiling  :", np.ceil(vals))    # round UP
print("Truncate :", np.trunc(vals))   # remove decimal

Original  : [  4   9  16  25  36  49  64  81 100]
Square root: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Log base e : [1.39 2.2  2.77 3.22 3.58 3.89 4.16 4.39 4.61]
Log base 10: [0.60205999 0.95424251 1.20411998 1.39794001 1.5563025  1.69019608
 1.80617997 1.90848502 2.        ]
Absolute   : [3 1 0 2 5]
Power of 2 : [ 16  81 256 625]

Original : [1.234 5.678 9.012 3.456]
Round 2  : [1.23 5.68 9.01 3.46]
Floor    : [1. 5. 9. 3.]
Ceiling  : [ 2.  6. 10.  4.]
Truncate : [1. 5. 9. 3.]


---
## Section 7 — Statistical Functions

### 7.1 Descriptive Statistics

These functions describe your data's **distribution** — the foundation of any analysis.

| Function | What it measures | Real-world use |
|----------|-----------------|----------------|
| `np.mean()` | Average value | Average order value |
| `np.median()` | Middle value | Median household income |
| `np.std()` | Spread of data | Consistency of production |
| `np.var()` | Variance (std²) | Risk in finance |
| `np.min/max()` | Extremes | Min/max temperature |
| `np.percentile()` | Position in distribution | Customer tier ranking |
| `np.sum()` | Total | Total revenue |

In [23]:
# Real scenario: Monthly revenue data for a year
revenue = np.array([45000, 52000, 48000, 61000, 55000, 70000,
                    68000, 72000, 63000, 58000, 49000, 75000])

print("=== Revenue Analysis ===")
print(f"Total Revenue     : ${np.sum(revenue):,}")
print(f"Monthly Average   : ${np.mean(revenue):,.0f}")
print(f"Median Month      : ${np.median(revenue):,.0f}")
print(f"Best Month        : ${np.max(revenue):,}")
print(f"Worst Month       : ${np.min(revenue):,}")
print(f"Std Deviation     : ${np.std(revenue):,.0f}")
print(f"Variance          : ${np.var(revenue):,.0f}")
print()

# 💡 Mean vs Median:
# - Mean is pulled by outliers
# - Median is resistant to outliers
# Example:
salaries = np.array([30000, 32000, 35000, 28000, 31000, 500000])  # CEO outlier
print(f"Salaries with CEO outlier:")
print(f"  Mean   = ${np.mean(salaries):,.0f}  ← pulled up by CEO")
print(f"  Median = ${np.median(salaries):,.0f}  ← more representative")

=== Revenue Analysis ===
Total Revenue     : $716,000
Monthly Average   : $59,667
Median Month      : $59,500
Best Month        : $75,000
Worst Month       : $45,000
Std Deviation     : $9,681
Variance          : $93,722,222

Salaries with CEO outlier:
  Mean   = $109,333  ← pulled up by CEO
  Median = $31,500  ← more representative


In [24]:
# ── PERCENTILES — very important for data analysts ─────────────────────
# np.percentile(array, q) → the value below which q% of data falls

customer_spending = np.array([120, 340, 85, 210, 450, 90, 175, 620,
                               310, 55, 280, 190, 780, 145, 230])

p25 = np.percentile(customer_spending, 25)   # Q1
p50 = np.percentile(customer_spending, 50)   # Q2 = Median
p75 = np.percentile(customer_spending, 75)   # Q3
p95 = np.percentile(customer_spending, 95)   # Top 5%

print("Customer Spending Percentiles:")
print(f"  25th percentile (Q1): ${p25:.0f}   ← 25% spend less than this")
print(f"  50th percentile (Q2): ${p50:.0f}   ← median spender")
print(f"  75th percentile (Q3): ${p75:.0f}   ← 75% spend less than this")
print(f"  95th percentile     : ${p95:.0f}   ← top 5% VIP customers")

IQR = p75 - p25
print(f"\nIQR (Q3 - Q1): ${IQR:.0f}   ← middle 50% range")

Customer Spending Percentiles:
  25th percentile (Q1): $132   ← 25% spend less than this
  50th percentile (Q2): $210   ← median spender
  75th percentile (Q3): $325   ← 75% spend less than this
  95th percentile     : $668   ← top 5% VIP customers

IQR (Q3 - Q1): $192   ← middle 50% range


In [25]:
# ── AXIS PARAMETER — crucial for 2D arrays ─────────────────────────────
# axis=0 → operate DOWN the rows (collapse rows, keep columns)
# axis=1 → operate ACROSS columns (collapse cols, keep rows)

#              Jan    Feb    Mar
sales = np.array([
    [5000, 4800, 5200],   # North
    [3200, 3500, 3100],   # South
    [4100, 3900, 4400],   # East
    [6200, 5800, 6100],   # West
])

# sum along axis=0: sum DOWN each column → total per month
monthly_total = np.sum(sales, axis=0)
print("Monthly totals (axis=0):", monthly_total)  # [18500 18000 18800]
print(" → Jan total:", monthly_total[0])
print()

# sum along axis=1: sum ACROSS each row → total per region
region_total = np.sum(sales, axis=1)
print("Region totals (axis=1):", region_total)   # [15000 9800 12400 18100]
print(" → North total:", region_total[0])
print()

# 💡 Memory trick:
# axis=0 → results have 1 value per COLUMN (shape matches columns)
# axis=1 → results have 1 value per ROW (shape matches rows)
print("Monthly averages:", np.mean(sales, axis=0))
print("Region averages :", np.mean(sales, axis=1))

Monthly totals (axis=0): [18500 18000 18800]
 → Jan total: 18500

Region totals (axis=1): [15000  9800 12400 18100]
 → North total: 15000

Monthly averages: [4625. 4500. 4700.]
Region averages : [5000.         3266.66666667 4133.33333333 6033.33333333]


---
## Section 8 — Sorting & Searching

### 8.1 Sorting Arrays

In [26]:
scores = np.array([78, 45, 92, 61, 88, 34, 75, 95, 51, 67])

# np.sort() — returns a NEW sorted array (doesn't change original)
sorted_asc  = np.sort(scores)           # ascending (default)
sorted_desc = np.sort(scores)[::-1]     # descending (reverse it)

print("Original   :", scores)
print("Ascending  :", sorted_asc)
print("Descending :", sorted_desc)
print()

# np.argsort() — returns INDICES that would sort the array
# Very useful: 'which student has the highest score?'
rank_indices = np.argsort(scores)       # indices of sorted order
rank_indices_desc = np.argsort(scores)[::-1]  # descending

print("Sorted indices (asc) :", rank_indices)
print("Top 3 student indices:", rank_indices_desc[:3])
print("Top 3 scores         :", scores[rank_indices_desc[:3]])

Original   : [78 45 92 61 88 34 75 95 51 67]
Ascending  : [34 45 51 61 67 75 78 88 92 95]
Descending : [95 92 88 78 75 67 61 51 45 34]

Sorted indices (asc) : [5 1 8 3 9 6 0 4 2 7]
Top 3 student indices: [7 2 4]
Top 3 scores         : [95 92 88]


In [27]:
# ── FINDING MIN/MAX POSITIONS ─────────────────────────────────────────────

monthly_sales = np.array([45000, 52000, 48000, 61000, 55000, 70000,
                           68000, 72000, 63000, 58000, 49000, 75000])
months = ['Jan','Feb','Mar','Apr','May','Jun',
          'Jul','Aug','Sep','Oct','Nov','Dec']

best_month_idx  = np.argmax(monthly_sales)   # index of max value
worst_month_idx = np.argmin(monthly_sales)   # index of min value

print(f"Best month : {months[best_month_idx]}  → ${monthly_sales[best_month_idx]:,}")
print(f"Worst month: {months[worst_month_idx]}  → ${monthly_sales[worst_month_idx]:,}")
print()

# np.unique() — find unique values and their counts
visit_hours = np.array([9, 14, 9, 22, 14, 9, 14, 3, 19, 22, 14, 9])
unique_hours, counts = np.unique(visit_hours, return_counts=True)

print("Unique hours:", unique_hours)
print("Visit counts:", counts)
print(f"Peak hour: {unique_hours[np.argmax(counts)]}:00 with {counts.max()} visits")

Best month : Dec  → $75,000
Worst month: Jan  → $45,000

Unique hours: [ 3  9 14 19 22]
Visit counts: [1 4 4 1 2]
Peak hour: 9:00 with 4 visits


In [28]:
# ── np.clip() — constrain values to a range ──────────────────────────────
# Real use: Sensor values outside valid range, percentages > 100

# Customer satisfaction ratings (should be 1-10, but some are erroneous)
ratings = np.array([8, 15, -2, 7, 10, 0, 6, 11, 9, 3])
valid_ratings = np.clip(ratings, 1, 10)  # clip to [1, 10]

print("Raw ratings  :", ratings)
print("Valid ratings:", valid_ratings)

Raw ratings  : [ 8 15 -2  7 10  0  6 11  9  3]
Valid ratings: [ 8 10  1  7 10  1  6 10  9  3]


---
## Section 9 — Reshaping & Stacking Arrays

### 9.1 Why Reshaping Matters

Real data often comes in the **wrong shape**. A survey result might be one flat list of numbers, but you need it as a table. Machine learning models expect specific input shapes. Reshaping is essential.

In [29]:
# ── reshape() ────────────────────────────────────────────────────────────
# Change shape WITHOUT changing data
# ⚠️ RULE: Total elements must stay the same!

# Survey data: 12 participants × 5 questions = 60 flat responses
np.random.seed(10)
flat_data = np.random.randint(1, 6, size=60)  # 60 values, 1-5
print("Flat (raw) data shape:", flat_data.shape)   # (60,)

# Reshape to (12 participants, 5 questions)
survey = flat_data.reshape(12, 5)
print("Reshaped survey shape:", survey.shape)      # (12, 5)
print("Survey data:\n", survey)
print()

# -1 means 'figure out this dimension automatically'
# Useful when you don't want to calculate one dimension manually
auto_reshape = flat_data.reshape(12, -1)  # NumPy figures out 60/12=5
print("Auto-reshape (12, -1):", auto_reshape.shape)

Flat (raw) data shape: (60,)
Reshaped survey shape: (12, 5)
Survey data:
 [[2 5 1 2 4]
 [5 2 1 2 3]
 [1 2 1 3 1]
 [5 4 1 5 4]
 [1 4 3 2 1]
 [5 2 4 4 2]
 [5 2 5 2 2]
 [5 4 3 1 4]
 [5 3 1 2 3]
 [1 1 4 2 4]
 [5 2 5 3 1]
 [1 5 5 1 1]]

Auto-reshape (12, -1): (12, 5)


In [30]:
# ── flatten() and ravel() — collapse to 1D ──────────────────────────────

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

flat1 = matrix.flatten()  # Always returns a COPY
flat2 = matrix.ravel()    # Returns a VIEW when possible (faster)

print("Matrix:\n", matrix)
print("Flatten:", flat1)
print("Ravel  :", flat2)

# 💡 Use flatten() when you need to modify without affecting original
# 💡 Use ravel() for performance when you only need to read

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flatten: [1 2 3 4 5 6 7 8 9]
Ravel  : [1 2 3 4 5 6 7 8 9]


In [31]:
# ── TRANSPOSE — flip rows and columns ───────────────────────────────────
# .T attribute or np.transpose()

#         Product1  Product2  Product3
data = np.array([
    [100, 200, 150],  # Store A
    [120, 180, 160],  # Store B
    [110, 220, 140],  # Store C
])

print("Original (stores × products):\n", data)
print("Shape:", data.shape)     # (3, 3)
print()
print("Transposed (products × stores):\n", data.T)
print("Shape:", data.T.shape)   # (3, 3) same here, but different for (3,5)

Original (stores × products):
 [[100 200 150]
 [120 180 160]
 [110 220 140]]
Shape: (3, 3)

Transposed (products × stores):
 [[100 120 110]
 [200 180 220]
 [150 160 140]]
Shape: (3, 3)


In [32]:
# ── STACKING ARRAYS ──────────────────────────────────────────────────────
# Combine multiple arrays into one

jan = np.array([5000, 3200, 4100, 6200])  # 4 regions, January
feb = np.array([4800, 3500, 3900, 5800])  # 4 regions, February
mar = np.array([5200, 3100, 4400, 6100])  # 4 regions, March

# np.vstack → stack VERTICALLY (add rows)
months_as_rows = np.vstack([jan, feb, mar])  # shape (3, 4)
print("vstack (months as rows):\n", months_as_rows)
print("Shape:", months_as_rows.shape)
print()

# np.hstack → stack HORIZONTALLY (add columns)
col1 = np.array([[1], [2], [3], [4]])
col2 = np.array([[10], [20], [30], [40]])
combined = np.hstack([col1, col2])
print("hstack (combined columns):\n", combined)
print("Shape:", combined.shape)
print()

# np.concatenate → more flexible, specify axis
full_quarter = np.concatenate([jan.reshape(1,-1), feb.reshape(1,-1), mar.reshape(1,-1)], axis=0)
print("Concatenated quarter:\n", full_quarter)

vstack (months as rows):
 [[5000 3200 4100 6200]
 [4800 3500 3900 5800]
 [5200 3100 4400 6100]]
Shape: (3, 4)

hstack (combined columns):
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]]
Shape: (4, 2)

Concatenated quarter:
 [[5000 3200 4100 6200]
 [4800 3500 3900 5800]
 [5200 3100 4400 6100]]


---
## Section 10 — Broadcasting

### 10.1 What is Broadcasting?

Broadcasting is NumPy's ability to perform operations on arrays of **different shapes** — without making copies of the data.

Think of it like this: If you have a column of prices and want to add tax, you don't need to repeat the tax rate for every single price. NumPy "broadcasts" the single value across the whole array.

### 10.2 Broadcasting Rules

NumPy compares shapes **from right to left**. Dimensions are compatible when:
1. They are **equal**, OR
2. One of them is **1**

```
Shape (4, 3) + Shape (3,) → broadcasts to (4, 3)  ✓
Shape (4, 1) + Shape (1, 3) → broadcasts to (4, 3)  ✓
Shape (4, 3) + Shape (4,)   → ERROR!  ✗
```

In [33]:
# ── SIMPLE BROADCASTING EXAMPLE ──────────────────────────────────────────

# Budget for each department (applied every month)
budget = np.array([10000, 8000, 12000, 9500])   # shape: (4,)

# Actual spending: 6 months × 4 departments
actual = np.array([
    [9800,  8200, 11500, 9000],   # Month 1
    [10200, 7900, 12400, 9800],   # Month 2
    [9500,  8100, 11800, 9300],   # Month 3
    [10500, 8300, 12100, 9700],   # Month 4
    [9900,  7800, 11600, 9100],   # Month 5
    [10100, 8050, 12300, 9600],   # Month 6
])  # shape: (6, 4)

# Broadcasting: (6, 4) - (4,) → NumPy broadcasts (4,) across each row
variance = actual - budget
print("Variance from budget (actual - budget):")
print(variance)
print()
print("Positive = overspent, Negative = underspent")
print()
print("Months with any department overspending:")
overspent_months = np.any(variance > 0, axis=1)
print(overspent_months)

Variance from budget (actual - budget):
[[-200  200 -500 -500]
 [ 200 -100  400  300]
 [-500  100 -200 -200]
 [ 500  300  100  200]
 [-100 -200 -400 -400]
 [ 100   50  300  100]]

Positive = overspent, Negative = underspent

Months with any department overspending:
[ True  True  True  True False  True]


In [34]:
# ── BROADCASTING VISUALIZATION ────────────────────────────────────────────
#
# Scenario: Calculate commission for each salesperson at different rates
#
#           Rate1%  Rate2%  Rate3%
rates = np.array([0.05, 0.07, 0.10])   # shape: (3,)

# Sales for 4 people
sales = np.array([
    [15000],  # Person A
    [22000],  # Person B
    [18500],  # Person C
    [9800],   # Person D
])  # shape: (4, 1)

# (4, 1) * (3,) → (4, 3): each person × each rate
commission_table = sales * rates
print("Commission table (4 people × 3 rates):")
print(commission_table)
print("Rows = people, Columns = rate scenarios")

Commission table (4 people × 3 rates):
[[ 750. 1050. 1500.]
 [1100. 1540. 2200.]
 [ 925. 1295. 1850.]
 [ 490.  686.  980.]]
Rows = people, Columns = rate scenarios


---
## Section 11 — Random Number Generation

### 11.1 Why Random Numbers?

As a data analyst you use random numbers to:
- **Simulate** data when you don't have real data
- Run **Monte Carlo simulations** for risk analysis
- Create **bootstrap samples** for confidence intervals
- **Test code** with predictable fake data

In [51]:
# ── SETTING A SEED — CRITICAL FOR REPRODUCIBILITY ─────────────────────
# A seed makes random numbers repeatable
# Always set a seed in analysis so results can be reproduced

np.random.seed(42)   # Any integer works
a = np.random.randint(1, 100, 5)
np.random.seed(42)   # Reset seed
b = np.random.randint(1, 100, 5)

print("Same seed → same numbers:", a)
print("                         :", b)
print("Arrays equal:", np.array_equal(a, b))

Same seed → same numbers: [52 93 15 72 61]
                         : [52 93 15 72 61]
Arrays equal: True


In [53]:
# ── KEY RANDOM FUNCTIONS ──────────────────────────────────────────────────

np.random.seed(0)

# 1. randint(low, high, size) — integers in [low, high)
scores = np.random.randint(40, 101, size=10)
print("Random scores (40-100):", scores)

# 2. random(size) — floats in [0, 1)
probabilities = np.random.random(5)
print("Random probs [0,1):    ", probabilities.round(3))

# 3. uniform(low, high, size) — floats in [low, high)
durations = np.random.uniform(20, 50, size=8)  # project durations
print("Project durations:     ", durations.round(1))

# 4. normal(mean, std, size) — bell curve (Gaussian)
# Most real-world data follows this distribution!
heights = np.random.normal(170, 10, size=1000) 
# mean=170cm, std=10
print(f"Heights: mean={heights.mean():.1f}cm, std={heights.std():.1f}cm")

# 5. binomial(n, p, size) — count of successes in n trials
# Perfect for A/B testing (did user convert: 0 or 1)
conversions = np.random.binomial(1, 0.40, size=500)  # 40% conversion rate
print(f"Conversion rate: {conversions.mean()*100:.1f}% (expected 40%)")

# 6. choice(array, size, replace) — random sampling
customers = np.arange(1, 101)  # Customer IDs 1-100
sample = np.random.choice(customers, size=10, replace=False)  # pick 10 unique
print(f"Random customer sample: {sample}")

Random scores (40-100): [84 87 93 40 43 99 43 79 49 59]
Random probs [0,1):     [0.646 0.438 0.892 0.964 0.383]
Project durations:      [43.8 35.9 37.  47.8 22.1 22.6 20.6 45. ]
Heights: mean=169.5cm, std=9.8cm
Conversion rate: 43.4% (expected 40%)
Random customer sample: [87 85 98 36 64 49 22 97 40 82]


---
## Section 12 — Handling Missing Data (NaN)

### 12.1 What is NaN?

`np.nan` stands for **Not a Number**. It represents missing or undefined values. Real-world data ALWAYS has missing values. Knowing how to handle NaN is essential.

⚠️ **NaN is contagious**: Any arithmetic with NaN returns NaN.

In [37]:
# NaN is contagious!
x = np.nan
print("nan + 5  =", x + 5)      # nan
print("nan > 3  =", x > 3)      # False
print("nan == nan =", x == x)   # False! Use np.isnan() instead
print("isnan(nan) =", np.isnan(x))  # True ← correct way to check

nan + 5  = nan
nan > 3  = False
nan == nan = False
isnan(nan) = True


In [38]:
# ── REAL-WORLD WORKFLOW: Sensor data cleaning ────────────────────────────

# Raw sensor readings (-999 = error code)
raw = np.array([72, 75, -999, 78, 80, 79, -999, 76, 74, 73,
                77, 81, 82, 80, 79, -999, 75, 74, 76, 78], dtype=float)

# Step 1: Replace error codes with NaN
clean = raw.copy()
clean[clean == -999] = np.nan
print("After replacing -999:", clean)
print()

# Step 2: Check how many are missing
missing_count = np.isnan(clean).sum()
valid_count   = (~np.isnan(clean)).sum()
print(f"Missing readings: {missing_count} / {len(clean)}")
print(f"Valid readings  : {valid_count}")
print()

# Step 3: Calculate stats IGNORING NaN (nan-safe functions)
print(f"Mean (with nan)   : {np.mean(clean):.1f}")      # nan! ← dangerous
print(f"Mean (nan-safe)   : {np.nanmean(clean):.1f}")   # correct
print(f"Median (nan-safe) : {np.nanmedian(clean):.1f}")
print(f"Std (nan-safe)    : {np.nanstd(clean):.2f}")
print(f"Sum (nan-safe)    : {np.nansum(clean):.0f}")
print()

# Step 4: Impute (fill) NaN with the mean
mean_val = np.nanmean(clean)
imputed = clean.copy()
imputed[np.isnan(imputed)] = mean_val
print(f"After imputation (filled with {mean_val:.1f}):", imputed)
print(f"Any NaN remaining? {np.isnan(imputed).any()}")

After replacing -999: [72. 75. nan 78. 80. 79. nan 76. 74. 73. 77. 81. 82. 80. 79. nan 75. 74.
 76. 78.]

Missing readings: 3 / 20
Valid readings  : 17

Mean (with nan)   : nan
Mean (nan-safe)   : 77.0
Median (nan-safe) : 77.0
Std (nan-safe)    : 2.85
Sum (nan-safe)    : 1309

After imputation (filled with 77.0): [72. 75. 77. 78. 80. 79. 77. 76. 74. 73. 77. 81. 82. 80. 79. 77. 75. 74.
 76. 78.]
Any NaN remaining? False


---
## Section 13 — Vectorization vs Loops

### 13.1 The Golden Rule of NumPy

> **If you're writing a Python `for` loop over a NumPy array, there's almost always a better way.**

Vectorization means applying operations to entire arrays at once. It's:
- **Faster** (C-level speed)
- **Cleaner** (less code)
- **Less error-prone** (no off-by-one bugs)

In [39]:
# ── COMPARISON: Loop vs Vectorized ───────────────────────────────────────
import time

data = np.random.random(1_000_000)

# Loop way
start = time.time()
result_loop = []
for x in data:
    result_loop.append(x ** 2 + 2 * x + 1)
loop_time = time.time() - start

# Vectorized way
start = time.time()
result_vec = data ** 2 + 2 * data + 1
vec_time = time.time() - start

print(f"Loop time       : {loop_time:.3f}s")
print(f"Vectorized time : {vec_time:.4f}s")
print(f"Speedup         : {loop_time/vec_time:.0f}x faster")

Loop time       : 0.688s
Vectorized time : 0.0144s
Speedup         : 48x faster


In [40]:
# ── PRACTICAL EXAMPLES: Replacing common loops ────────────────────────────

prices = np.array([100, 250, 80, 340, 150, 90, 200])
quantities = np.array([5, 2, 10, 1, 3, 8, 4])

# ❌ Loop approach
total_loop = []
for p, q in zip(prices, quantities):
    total_loop.append(p * q)

# ✅ Vectorized approach
total_vec = prices * quantities

print("Revenue per product:", total_vec)
print("Total revenue      :", total_vec.sum())
print()

# ❌ Conditional loop
discounts_loop = []
for p in prices:
    if p > 150:
        discounts_loop.append(p * 0.10)
    else:
        discounts_loop.append(0)

# ✅ Vectorized with np.where
discounts_vec = np.where(prices > 150, prices * 0.10, 0)
print("Discount per product:", discounts_vec)

Revenue per product: [500 500 800 340 450 720 800]
Total revenue      : 4110

Discount per product: [ 0. 25.  0. 34.  0.  0. 20.]


---
## Section 14 — Advanced Statistics

### 14.1 Normalization and Standardization

Before comparing or feeding data into models, you often need to rescale it.

| Method | Formula | Result Range | Use Case |
|--------|---------|-------------|----------|
| Min-Max Normalization | `(x - min) / (max - min)` | [0, 1] | When you need values between 0 and 1 |
| Z-score Standardization | `(x - mean) / std` | Mean=0, Std=1 | When comparing across different scales |

In [41]:
# Real scenario: Normalize exam scores for comparison across subjects
np.random.seed(42)
scores = np.random.randint(30, 100, size=20)

# Min-Max Normalization: scales to [0, 1]
min_val = scores.min()
max_val = scores.max()
normalized = (scores - min_val) / (max_val - min_val)

# Z-score Standardization: mean=0, std=1
mean_val = scores.mean()
std_val  = scores.std()
standardized = (scores - mean_val) / std_val

print("Original scores  :", scores)
print("Min-Max [0,1]    :", normalized.round(3))
print("Z-scores         :", standardized.round(3))
print()
print(f"Normalized: min={normalized.min():.1f}, max={normalized.max():.1f}")
print(f"Z-score:    mean={standardized.mean():.10f} ≈ 0")
print(f"            std ={standardized.std():.10f} ≈ 1")

Original scores  : [81 44 90 50 53 32 51 82 31 59 67 31 93 89 50 62 87 51 78 88]
Min-Max [0,1]    : [0.806 0.21  0.952 0.306 0.355 0.016 0.323 0.823 0.    0.452 0.581 0.
 1.    0.935 0.306 0.5   0.903 0.323 0.758 0.919]
Z-scores         : [ 0.849 -0.941  1.285 -0.651 -0.506 -1.522 -0.602  0.898 -1.57  -0.215
  0.172 -1.57   1.43   1.236 -0.651 -0.07   1.14  -0.602  0.704  1.188]

Normalized: min=0.0, max=1.0
Z-score:    mean=-0.0000000000 ≈ 0
            std =1.0000000000 ≈ 1


In [42]:
# ── CORRELATION ─────────────────────────────────────────────────────────
# Pearson Correlation: measures LINEAR relationship between two variables
# Range: -1 (perfect negative) to +1 (perfect positive), 0 = no relationship

ad_spend = np.array([200, 250, 180, 300, 350, 400, 420, 390, 310, 270, 230, 200])
revenue  = np.array([820, 910, 780, 1050, 1200, 1350, 1400, 1280, 1050, 950, 870, 810])

# Manual Pearson correlation
def pearson_corr(x, y):
    n = len(x)
    numerator = np.sum((x - x.mean()) * (y - y.mean()))
    denominator = np.sqrt(np.sum((x - x.mean())**2) * np.sum((y - y.mean())**2))
    return numerator / denominator

r = pearson_corr(ad_spend, revenue)

# Built-in way: np.corrcoef returns a 2×2 correlation matrix
corr_matrix = np.corrcoef(ad_spend, revenue)

print(f"Manual Pearson r        : {r:.4f}")
print(f"np.corrcoef result      :\n{corr_matrix}")
print(f"Correlation coefficient : {corr_matrix[0, 1]:.4f}")
print()
print("Interpretation:")
if abs(r) > 0.7:
    print(f"  r = {r:.2f} → STRONG {'positive' if r > 0 else 'negative'} correlation")
elif abs(r) > 0.4:
    print(f"  r = {r:.2f} → MODERATE correlation")
else:
    print(f"  r = {r:.2f} → WEAK correlation")

Manual Pearson r        : 0.9940
np.corrcoef result      :
[[1.         0.99399713]
 [0.99399713 1.        ]]
Correlation coefficient : 0.9940

Interpretation:
  r = 0.99 → STRONG positive correlation


In [43]:
# ── LINEAR REGRESSION with np.polyfit ───────────────────────────────────
# Find the best-fit line: y = slope * x + intercept
# degree=1 means linear (straight line)

# Fit the line
slope, intercept = np.polyfit(ad_spend, revenue, deg=1)
print(f"Regression line: Revenue = {slope:.2f} × AdSpend + {intercept:.2f}")
print()

# Make predictions
predicted = slope * ad_spend + intercept

# Predict for a new value
new_ad_spend = 500
predicted_revenue = slope * new_ad_spend + intercept
print(f"If ad spend = ${new_ad_spend}, predicted revenue = ${predicted_revenue:.0f}")
print()

# Model quality: RMSE (lower = better)
residuals = revenue - predicted
rmse = np.sqrt(np.mean(residuals**2))
print(f"Residuals (actual - predicted): {residuals.round(0)}")
print(f"RMSE: ${rmse:.2f} (average prediction error)")

Regression line: Revenue = 2.61 × AdSpend + 277.03

If ad spend = $500, predicted revenue = $1584

Residuals (actual - predicted): [ 20. -20.  33. -11.   8.  28.  25. -16. -37. -33.  -8.  10.]
RMSE: $23.03 (average prediction error)


In [44]:
# ── OUTLIER DETECTION using IQR method ───────────────────────────────────
# Points outside [Q1 - 1.5×IQR, Q3 + 1.5×IQR] are outliers
# This is the same rule used by box plots

np.random.seed(7)
spending = np.random.normal(250, 80, 1000).clip(0)

Q1  = np.percentile(spending, 25)
Q3  = np.percentile(spending, 75)
IQR = Q3 - Q1

lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

outliers = spending[(spending < lower_fence) | (spending > upper_fence)]

print(f"Q1 = ${Q1:.2f}")
print(f"Q3 = ${Q3:.2f}")
print(f"IQR = ${IQR:.2f}")
print(f"Outlier fences: [${lower_fence:.2f}, ${upper_fence:.2f}]")
print(f"Number of outliers: {len(outliers)}")
print(f"Outlier avg spending: ${outliers.mean():.2f}")

Q1 = $196.99
Q3 = $300.99
IQR = $104.00
Outlier fences: [$40.99, $456.99]
Number of outliers: 8
Outlier avg spending: $186.31


---
## Section 15 — Linear Algebra Basics

### 15.1 Why Linear Algebra for Analysts?

You don't need to be a mathematician. But understanding a few key operations helps with:
- **Matrix multiplication** (combining data tables)
- **Dot products** (weighted scores, similarity)
- **Solving equations** (optimization, regression)

In [45]:
# ── DOT PRODUCT ──────────────────────────────────────────────────────────
# Multiply element-by-element and sum the results
# Real use: weighted average score

# A student's scores on 3 components
scores  = np.array([85, 72, 91])      # quiz, midterm, final
weights = np.array([0.20, 0.30, 0.50]) # 20%, 30%, 50%

# Weighted average using dot product
final_grade = np.dot(scores, weights)
print(f"Scores : {scores}")
print(f"Weights: {weights}")
print(f"Weighted grade: {final_grade:.1f}")
print(f"Manual check: {85*0.20 + 72*0.30 + 91*0.50}")

Scores : [85 72 91]
Weights: [0.2 0.3 0.5]
Weighted grade: 84.1
Manual check: 84.1


In [46]:
# ── MATRIX MULTIPLICATION ─────────────────────────────────────────────────
# np.dot(A, B) or A @ B (Python 3.5+)
# Rule: A.shape (m, n) × B.shape (n, p) → result.shape (m, p)
#       The INNER dimensions must match!

# Scenario: Calculate revenue for 3 regions × 4 products
# Quantity sold (3 regions × 4 products)
quantity = np.array([
    [100, 200, 150, 80],   # Region A
    [120, 180, 160, 90],   # Region B
    [110, 220, 140, 70],   # Region C
])  # shape (3, 4)

# Product prices (4 products × 1)
prices = np.array([10, 25, 15, 40])   # shape (4,)

# Revenue per region = quantity @ prices
# (3, 4) @ (4,) → (3,)
revenue = quantity @ prices
print("Revenue per region:", revenue)
print("Manual check Region A:", 100*10 + 200*25 + 150*15 + 80*40)

Revenue per region: [11450 11700 11500]
Manual check Region A: 11450


---
## Section 16 — Simulation & Monte Carlo

### 16.1 What is Monte Carlo Simulation?

Run an experiment thousands of times with random inputs to estimate **probabilities and risks**.

**Real business example**: "What's the probability our project finishes on time?"

In [47]:
# ── MONTE CARLO: Project Completion Risk ────────────────────────────────

np.random.seed(0)
N = 100_000   # number of simulations

# Project duration is uncertain: uniformly between 20 and 50 days
durations = np.random.uniform(20, 50, size=N)

# What's the probability of finishing in 35 days or less?
deadline = 35
prob_on_time = (durations <= deadline).mean() * 100

print(f"=== Monte Carlo Project Analysis ({N:,} simulations) ===")
print(f"Mean duration     : {durations.mean():.1f} days")
print(f"Std deviation     : {durations.std():.1f} days")
print(f"P(finish ≤ 35 days): {prob_on_time:.1f}%")
print()

# What deadline guarantees 90% chance of completion?
p90_deadline = np.percentile(durations, 90)
print(f"For 90% confidence, set deadline at: {p90_deadline:.1f} days")

# Within 1 standard deviation
mean  = durations.mean()
std   = durations.std()
within_1sd = ((durations >= mean - std) & (durations <= mean + std)).mean() * 100
print(f"Within 1 std dev  : {within_1sd:.1f}% (normal distribution → ~68%)")

=== Monte Carlo Project Analysis (100,000 simulations) ===
Mean duration     : 35.0 days
Std deviation     : 8.7 days
P(finish ≤ 35 days): 50.1%

For 90% confidence, set deadline at: 47.0 days
Within 1 std dev  : 57.6% (normal distribution → ~68%)


In [48]:
# ── BOOTSTRAP RESAMPLING — estimate confidence intervals ─────────────────
# Core idea: randomly resample your data (with replacement) many times
# to estimate uncertainty in your statistics

# Real scenario: A/B test — does green button convert better than blue?
np.random.seed(21)

# Simulate user conversions (1=converted, 0=not)
group_A = np.random.binomial(1, 0.40, 500)  # Blue button, 40% true rate
group_B = np.random.binomial(1, 0.45, 500)  # Green button, 45% true rate

observed_rate_A = group_A.mean()
observed_rate_B = group_B.mean()
observed_lift   = observed_rate_B - observed_rate_A

print(f"Group A conversion rate: {observed_rate_A*100:.1f}%")
print(f"Group B conversion rate: {observed_rate_B*100:.1f}%")
print(f"Observed lift          : {observed_lift*100:.2f}%")
print()

# Bootstrap 1000 times to build confidence interval
n_bootstrap = 1000
boot_diffs = np.zeros(n_bootstrap)

for i in range(n_bootstrap):
    # Resample with replacement
    sample_A = np.random.choice(group_A, size=500, replace=True)
    sample_B = np.random.choice(group_B, size=500, replace=True)
    boot_diffs[i] = sample_B.mean() - sample_A.mean()

# 95% confidence interval
ci_low  = np.percentile(boot_diffs, 2.5)
ci_high = np.percentile(boot_diffs, 97.5)

print(f"95% Bootstrap CI for lift: [{ci_low*100:.2f}%, {ci_high*100:.2f}%]")
print()
if ci_low > 0:
    print("✅ CI excludes 0 → statistically significant! Green button IS better.")
else:
    print("❌ CI includes 0 → not conclusive. Need more data.")

Group A conversion rate: 43.2%
Group B conversion rate: 42.8%
Observed lift          : -0.40%

95% Bootstrap CI for lift: [-6.80%, 5.61%]

❌ CI includes 0 → not conclusive. Need more data.


---
## Section 17 — Putting It All Together

### 17.1 Complete Data Analysis Workflow

Let's simulate a real end-to-end analysis: **Monthly sales performance review**

In [49]:
# ── COMPLETE WORKFLOW: Sales Performance Dashboard ───────────────────────

np.random.seed(99)

# === DATA GENERATION (simulating real data) ===
n_salespeople = 10
n_months = 12

# Sales matrix: 10 salespeople × 12 months
base_sales = np.random.normal(50000, 15000, size=(n_salespeople, n_months))
base_sales = np.clip(base_sales, 10000, None)  # No negative sales
base_sales = np.round(base_sales, -2)          # Round to nearest 100

print("=" * 55)
print("      ANNUAL SALES PERFORMANCE REPORT")
print("=" * 55)

# === STEP 1: Basic summary ===
annual_per_person = base_sales.sum(axis=1)    # sum across months
monthly_total     = base_sales.sum(axis=0)    # sum across people
grand_total       = base_sales.sum()

print(f"\nGrand Total Revenue : ${grand_total:>12,.0f}")
print(f"Average per person  : ${annual_per_person.mean():>12,.0f}")
print(f"Best month total    : ${monthly_total.max():>12,.0f}")
print(f"Worst month total   : ${monthly_total.min():>12,.0f}")

# === STEP 2: Identify top and bottom performers ===
top_idx    = np.argmax(annual_per_person)
bottom_idx = np.argmin(annual_per_person)

print(f"\nTop performer     : Salesperson {top_idx+1} → ${annual_per_person[top_idx]:,.0f}")
print(f"Bottom performer  : Salesperson {bottom_idx+1} → ${annual_per_person[bottom_idx]:,.0f}")

# === STEP 3: Quota analysis ===
quota = 45000  # Monthly quota per person
quota_met = base_sales >= quota                         # boolean mask
quota_rate_per_person = quota_met.mean(axis=1) * 100   # % months meeting quota

print(f"\nQuota Attainment (≥ ${quota:,}/month):")
for i, rate in enumerate(quota_rate_per_person):
    bar = '█' * int(rate / 10)
    print(f"  Person {i+1:2d}: {bar:<10} {rate:.0f}%")

# === STEP 4: Percentile ranking ===
p75 = np.percentile(annual_per_person, 75)
top_performers = annual_per_person[annual_per_person >= p75]
print(f"\nTop 25% threshold: ${p75:,.0f}")
print(f"Top performers   : {len(top_performers)} salespeople")

# === STEP 5: Month-over-month growth ===
monthly_avg = base_sales.mean(axis=0)
mom_growth  = np.diff(monthly_avg) / monthly_avg[:-1] * 100
best_growth_month = np.argmax(mom_growth) + 2  # +2 because diff shifts index

print(f"\nMonth-over-month growth rates (avg across team):")
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
for i, g in enumerate(mom_growth):
    symbol = '▲' if g >= 0 else '▼'
    print(f"  {months[i]}→{months[i+1]}: {symbol} {abs(g):.1f}%")

print("\n" + "=" * 55)
print("             END OF REPORT")
print("=" * 55)

      ANNUAL SALES PERFORMANCE REPORT

Grand Total Revenue : $   6,210,200
Average per person  : $     621,020
Best month total    : $     563,700
Worst month total   : $     415,300

Top performer     : Salesperson 9 → $741,000
Bottom performer  : Salesperson 4 → $549,600

Quota Attainment (≥ $45,000/month):
  Person  1: █████████  92%
  Person  2: █████      58%
  Person  3: ██████     67%
  Person  4: ████       42%
  Person  5: ████████   83%
  Person  6: █████      50%
  Person  7: ███████    75%
  Person  8: ██████     67%
  Person  9: ████████   83%
  Person 10: ████████   83%

Top 25% threshold: $641,725
Top performers   : 3 salespeople

Month-over-month growth rates (avg across team):
  Jan→Feb: ▲ 23.3%
  Feb→Mar: ▼ 10.2%
  Mar→Apr: ▲ 22.5%
  Apr→May: ▼ 2.6%
  May→Jun: ▲ 2.8%
  Jun→Jul: ▼ 13.9%
  Jul→Aug: ▲ 7.6%
  Aug→Sep: ▲ 0.1%
  Sep→Oct: ▲ 3.2%
  Oct→Nov: ▼ 1.2%
  Nov→Dec: ▲ 1.8%

             END OF REPORT


---
## 📖 Quick Reference Cheat Sheet

### Array Creation
```python
np.array([1,2,3])           # from list
np.zeros((3,4))             # 3×4 zeros
np.ones((2,3))              # 2×3 ones
np.arange(0, 10, 2)         # [0,2,4,6,8]
np.linspace(0, 1, 5)        # 5 evenly spaced in [0,1]
np.random.randint(0,10,5)   # 5 random ints 0-9
np.random.normal(0,1,100)   # 100 values, mean=0, std=1
```

### Indexing
```python
a[0]           # first element
a[-1]          # last element
a[2:5]         # elements 2,3,4
a[::2]         # every 2nd element
a[a > 10]      # filter: elements > 10
a[np.where(a > 10)]  # same, explicit
m[0, :]        # first row of 2D array
m[:, 1]        # second column of 2D array
```

### Statistics
```python
np.mean(a)       np.median(a)
np.std(a)        np.var(a)
np.min(a)        np.max(a)
np.sum(a)        np.cumsum(a)
np.percentile(a, 75)      # 75th percentile
np.nanmean(a)             # mean ignoring NaN
np.corrcoef(x, y)         # correlation matrix
np.polyfit(x, y, 1)       # linear regression
```

### Shape & Reshape
```python
a.shape          a.ndim          a.size
a.reshape(3,4)   a.flatten()     a.T
np.vstack([a,b]) np.hstack([a,b])
```

### Math & Logic
```python
np.sqrt(a)   np.abs(a)   np.log(a)   np.round(a,2)
np.where(a>0, 'pos', 'neg')   # vectorized if/else
np.clip(a, 0, 100)             # constrain to [0,100]
np.diff(a)                     # differences between elements
(a > 0).sum()                  # count True values
(a > 0).mean()                 # proportion of True values
```

### NaN Handling
```python
np.isnan(a)         # boolean mask of NaN positions
np.nanmean(a)       # mean ignoring NaN
np.nansum(a)        # sum ignoring NaN
a[np.isnan(a)] = 0  # replace NaN with 0
```

---

## 🎯 Skill-to-Problem Mapping

| Problem Set | Key Skills Needed |
|-------------|------------------|
| P1-P2 | Section 2, 5, 7 (array creation, filtering, stats) |
| P3-P4 | Section 6 (vectorized math operations) |
| P5-P6 | Section 5, 7, 8 (boolean indexing, stats, sorting) |
| P7-P8 | Section 3, 7, 12 (2D arrays, axis, NaN handling) |
| P9 | Section 14 (normalization, standardization) |
| P10 | Section 6, 5 (arithmetic, boolean indexing) |
| P11 | Section 9, 7 (reshape, axis aggregation) |
| P12 | Section 8, 6 (np.diff, sorting, argmax) |
| P13 | Section 10 (broadcasting) |
| P14 | Section 14 (correlation, linear regression) |
| P15 | Section 7, 14 (percentiles, IQR, outliers) |
| P16 | Section 4, 5, 9 (indexing, masking, reshape) |
| P17 | Section 16 (Monte Carlo, np.random.uniform) |
| P18 | Section 10, 7 (broadcasting, axis, argmax) |
| P19 | Section 8, 7 (np.diff, aggregation) |
| P20 | Section 11, 16 (np.random.binomial, bootstrap CI) |

---

## 🚀 What to Practice Next

1. **Solve all 20 problems** in the companion notebook using what you learned here
2. **Connect to Pandas** — every DataFrame operation uses NumPy arrays underneath
3. **Connect to Matplotlib** — plotting functions accept NumPy arrays directly
4. **Try real datasets** — download any CSV from Kaggle and analyze with NumPy

---
*You now have everything you need. The best way to learn is to run every cell, break things, and fix them. Happy analyzing!* 🔢